version: '3.8'

networks:
    app-network:
        driver: bridge

services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - ./laravel:/var/www/html
        ports:
            - "8000:8000"
        working_dir: /var/www/html
        networks:
            - app-network
        depends_on:
            - db
        command: php artisan serve --host=0.0.0.0 --port=8000

    db:
        image: mariadb:10.9
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

volumes:
    db_data:
