version: '3'
services:
    php:
        build: .
        networks:
            - backend
        expose:
            - "9000"
        volumes:
            - .:/var/www/html
    nginx:
        image: nginx:mainline-alpine
        networks:
          - backend
        ports:
          - '80:80'
          - '443:443'
        restart: on-failure
        volumes:
          - .:/var/www/html
          - ./nginx_config.conf:/etc/nginx/conf.d/site.conf
          - ./ssl:/etc/nginx/ssl
        links:
            - php
        depends_on:
            - php
    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - backend
        ports:
            - '3306:3306'
        restart: on-failure
        volumes:
            - databaseVolume:/var/lib/mysql
volumes:
    databaseVolume: {}
networks:
    backend:
        driver: bridge