version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
        - laravel

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
        - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
        - laravel

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
        - laravel

volumes:
  dbdata:
  certbot-etc:
  certbot-var:

networks:
  laravel: